### PR TITLE
Fix sorter and eject

### LINKED ISSUE #30: Filter doesn't work anymore
Minetest 5.9.0, Ubuntu 22.04, Whynot game, hopper at 18f3711 (edit: also at 0baf36e)

The filter doesn't work as described anymore. Items listed in the filter do go through in the direction of the big V, but items that don't match just accumulate in the 4 storage spot and end up clogging instead going out the secondary output. Toggling the ejection button has no effect.

Here is the setup I used:

screenshot_20240830_204856

And this is what happens:

screenshot_20240830_204912

I bisected the main branch and found the regression was in this commit:
```
30b565480212299bca9a22ece614ff238777bbb3 is the first bad commit
commit 30b565480212299bca9a22ece614ff238777bbb3
Author: SmallJoker <mk939@ymail.com>
Date:   Fri Aug 16 22:58:59 2024 +0200

    Add .luacheckrc and fix its warnings

 .luacheckrc       | 22 ++++++++++++++++++++++
 abms.lua          |  4 ++--
 crafts.lua        | 10 +++++-----
 nodes/chute.lua   |  3 ---
 nodes/hoppers.lua |  8 ++++----
 nodes/sorter.lua  | 47 ++++++++++++++---------------------------------
 utility.lua       |  5 ++---
 7 files changed, 49 insertions(+), 50 deletions(-)
 create mode 100644 .luacheckrc
```

### LINKED ISSUE #31: Crash with filter eject
Ubuntu 22.04, Minetest 5.9.0, WhyNot game, hopper at 0baf36e

I removed the secondary exit pipe on the filter (see picture in #30) and now it crashes when I set the filter to eject.
```
AsyncErr: Lua: Runtime error from mod 'hopper' in callback node_on_timer(): ...minetest/games/whynot-game/mods/tools/hopper/utility.lua:155: attempt to index local 'target_inv_info' (a nil value)
stack traceback:
	...minetest/games/whynot-game/mods/tools/hopper/utility.lua:155: in function 'try_send_item'
	...est/games/whynot-game/mods/tools/hopper/nodes/sorter.lua:192: in function <...est/games/whynot-game/mods/tools/hopper/nodes/sorter.lua:150>
```

I bisected the main branch and found the regression happened in the following commit:
```
df5f8d837932dc70a812b850ef9b78ee3733111d is the first bad commit
commit df5f8d837932dc70a812b850ef9b78ee3733111d
Author: Ajrat Makhmutov <rauty@altlinux.org>
Date:   Sun Jul 21 04:16:35 2024 +0300

    Add multi-node containers support
    
    + remove trailing spaces
    + add new api for extra information about containers

 abms.lua          |  12 ++---
 api.lua           | 130 ++++++++++++++++++++++++++++++++++++++----------------
 nodes/chute.lua   |  12 ++---
 nodes/hoppers.lua |  28 +++++++-----
 nodes/sorter.lua  |  42 +++++++++---------
 utility.lua       |  64 ++++++++++++++++++---------
 6 files changed, 184 insertions(+), 104 deletions(-)
```

### PR DESCRIPTION
**Pull request by dacmot**
Fixes #30
Fixes #31 

Also corrects eject for sorter, and simplifies it.

I couldn't figure out how to get the hopper to eject as well. I thought that was controlled by the abm but the modifications did not seem to do anything.

### CODE REVIEW

File: nodes/sorter.lua [hunk 1]
```diff
@@ -175,21 +175,23 @@ minetest.register_node("hopper:sorter", {
...
 			local dst_node = minetest.get_node(dst_pos)
 			local registered_inventories = hopper.get_registered(dst_node.name)
 
 			if registered_inventories ~= nil then
-				return hopper.send_item_to(pos, dst_pos, dst_node, registered_inventories[output_dir], filter_items)
+				return hopper.send_item_to(pos, dst_pos, dst_node, registered_inventories[output_dir], filter_items_map)
 			end
 
-			return hopper.send_item_to(pos, dst_pos, dst_node, nil, filter_items)
+			return hopper.eject_item(pos, dst_pos)
```
Comment (SmallJoker) [inline nodes/sorter.lua]: This line is redundant due to L193. If you'd like to keep this one here, the function would be more appropriately named `try_send_or_eject`.

File: utility.lua [hunk 2]
```diff
@@ -204,10 +218,19 @@ hopper.send_item_to = function(hopper_pos, target_pos, target_node, target_inv_i
...
-	end
-
 	return false
 end
+
+hopper.eject_item = function(hopper_pos, target_pos)
+	if hopper.config.eject_button_enabled then
+
+		local hopper_meta = minetest.get_meta(hopper_pos)
+		if hopper_meta:get_string("eject") == "true" then
```
Comment (SmallJoker) [inline utility.lua]:
```suggestion
hopper.eject_item = function(hopper_pos, target_pos)
	if not hopper.config.eject_button_enabled then
		return false
	end

	local hopper_meta = minetest.get_meta(hopper_pos)
	if hopper_meta:get_string("eject") ~= "true" then
		return false
	end
```

....
```Lua
	return send_item_to_air(hopper_inv, target_pos)
```

1. It's always helpful to have a success/failure indicator
2. Early returns make the code easier to read. Less need to keep track of indent levels.
3. The function might be more intuitive if it were named `try_eject_item` since fail/success is heavily dependent on the hopper configuration.

File: utility.lua [hunk 3]
```diff
@@ -129,25 +129,39 @@ hopper.take_item_from = function(hopper_pos, target_pos, target_node, target_inv
...
+		if item ~= "" then
 			stack_num = i
 			break
 		end
 	end
-	if not stack_num then
-		return false
+
+	local eject_node = minetest.get_node(target_pos)
+	if (eject_node["name"] ~= "air") then
```
Comment (SmallJoker) [inline utility.lua]: Ejecting to any non-solids should be fine. This also closely follows the now deleted code in `hopper.send_item_to`.

```Lua
local ndef = minetest.registered_nodes[eject_node.name]
if not ndef or not ndef.buildable_to then
```

File: utility.lua [hunk 4]
```diff
@@ -129,25 +129,39 @@ hopper.take_item_from = function(hopper_pos, target_pos, target_node, target_inv
...
+local function send_item_to_air(hopper_inv, target_pos)
+	local item
 	local stack
 	local stack_num
 	for i = 1, hopper_inv:get_size("main") do
 		stack = hopper_inv:get_stack("main", i)
-		local item = stack:get_name()
-		if item ~= "" and (filtered_items == nil or filtered_items[item]) then
+		item = stack:get_name()
+		if item ~= "" then
```
Comment (SmallJoker) [inline utility.lua]: Duplicated variable. No need to track `item` separately when you can do it like this:
```Lua
if  not stack:is_empty()
```
The logging function below would then use `stack:get_name()`.

File: utility.lua [hunk 5]
```diff
@@ -129,25 +129,39 @@ hopper.take_item_from = function(hopper_pos, target_pos, target_node, target_inv
...
+
+	local eject_node = minetest.get_node(target_pos)
+	if (eject_node["name"] ~= "air") then
+		minetest.log("verbose", "hopper.send_item_to_air: eject direction not air ("..eject_node["name"].." at "..target_pos:to_string().."). Looking for alternate.")
+		local air_pos
+		local radius = 1
+		while not air_pos and radius <= 5 do
+			air_pos = minetest.find_node_near(target_pos, radius, {"air"})
+			radius = radius + 1
+		end
```
Comment (SmallJoker) [inline utility.lua]: Inefficient. Plenty of nodes will be checked multiple times. Checking with radius 2 once should be enough. Indicate failure by return value.

File: nodes/sorter.lua (hunk 1 above)
Comment (dacmot) [reply nodes/sorter.lua]: Replaced with `return false`

File: utility.lua (hunk 2 above)
Comment (dacmot) [reply utility.lua]: All good advice. Thank you.

File: utility.lua (hunk 3 above)
Comment (dacmot) [reply utility.lua]: Good thinking. I may have replaced it after doing the find node for air...

File: utility.lua (hunk 4 above)
Comment (dacmot) [reply utility.lua]: Removed.

File: utility.lua (hunk 5 above)
Comment (dacmot) [reply utility.lua]: Right... newbie me. Over-complicated for no good reason.

**Review by SmallJoker — APPROVED** [review]
Works. Will merge in a few days unless there are objections.
